### PR TITLE
Fix fallback loading from referrers api

### LINKED ISSUE #36: Call to a member function getColumn() on null
```
Error: {"message":"Call to a member function getColumn() on null","file":"\/var\/www\/html\/plugins\/Referrers\/API.php","line":380,"request_id":"5e936","backtrace":" on \/var\/www\/html\/plugins\/Referrers\/API.php(380)
0 \/var\/www\/html\/plugins\/MarketingCampaignsReporting\/API.php(53): Piwik\\Plugins\\Referrers\\API->getKeywordsFromCampaignId('1', 'day', '2020-02-15,2020...', '20', false)
1 [internal function]: Piwik\\Plugins\\MarketingCampaignsReporting\\API->getKeywordContentFromNameId('1', 'day', '2020-02-15,2020...', '20', false)
2 \/var\/www\/html\/core\/API\/Proxy.php(237): call_user_func_array(Array, Array)
3 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()
4 \/var\/www\/html\/core\/API\/Proxy.php(328): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))
5 \/var\/www\/html\/core\/API\/Request.php(266): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getKeywordConte...', Array)
6 \/var\/www\/html\/plugins\/API\/RowEvolution.php(300): Piwik\\API\\Request->process()
7 \/var\/www\/html\/plugins\/API\/RowEvolution.php(57): Piwik\\Plugins\\API\\RowEvolution->loadRowEvolutionDataFromAPI(Array, 1, 'day', '2020-02-15,2020...', 'MarketingCampai...', 'getKeywordConte...', Array, false, Array)
8 \/var\/www\/html\/plugins\/API\/API.php(507): Piwik\\Plugins\\API\\RowEvolution->getRowEvolution(1, 'day', '2020-02-15,2020...', 'MarketingCampai...', 'getKeywordConte...', 'postcard-2020-d...', false, false, false, Array, true, true, false)
9 [internal function]: Piwik\\Plugins\\API\\API->getRowEvolution(1, 'range', '2020-02-15,2020...', 'MarketingCampai...', 'getKeywordConte...', 'postcard-2020-d...', false, false, false, false, true, true, false, false)
10 \/var\/www\/html\/core\/API\/Proxy.php(237): call_user_func_array(Array, Array)
11 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()
12 \/var\/www\/html\/core\/API\/Proxy.php(328): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))
13 \/var\/www\/html\/core\/API\/Request.php(266): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getRowEvolution', Array)
14 \/var\/www\/html\/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(208): Piwik\\API\\Request->process()
15 \/var\/www\/html\/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(117): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->loadEvolutionReport()
16 \/var\/www\/html\/plugins\/CoreHome\/Controller.php(244): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->__construct(1, NULL, NULL)
17 \/var\/www\/html\/plugins\/CoreHome\/Controller.php(210): Piwik\\Plugins\\CoreHome\\Controller->makeRowEvolution(false)
18 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->getRowEvolutionPopover()
19 \/var\/www\/html\/core\/FrontController.php(589): call_user_func_array(Array, Array)
20 \/var\/www\/html\/core\/FrontController.php(165): Piwik\\FrontController->doDispatch('CoreHome', 'getRowEvolution...', Array)
21 \/var\/www\/html\/core\/dispatch.php(34): Piwik\\FrontController->dispatch()
22 \/var\/www\/html\/index.php(27): require_once('\/var\/www\/html\/c...')
23 {main}"}
```

URL: https://x/index.php?date=2020-02-15,2020-02-24&apiMethod=MarketingCampaignsReporting.getKeywordContentFromNameId&label=postcard-2020-deferrednews+%3E+%40qr-code-open&disableLink=1&module=CoreHome&action=getRowEvolutionPopover&colors=%7B%22backgroundColor%22%3A%22%23ffffff%22%2C%22lineColor%22%3A%22%23162c4a%22%2C%22minPointColor%22%3A%22%23ff7f7f%22%2C%22maxPointColor%22%3A%22%2375bf7c%22%2C%22lastPointColor%22%3A%22%2355aaff%22%2C%22fillColor%22%3A%22%23ffffff%22%7D&idSubtable=20&idSite=1&period=range

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #36

### CODE REVIEW

File: API.php [hunk 1]
```diff
@@ -50,8 +50,20 @@ public function getKeywordContentFromNameId($idSite, $period, $date, $idSubtable
         $dataTable = $this->getDataTable(Archiver::CAMPAIGN_NAME_RECORD_NAME, $idSite, $period, $date, $segment, $expanded = false, $idSubtable);
 
         if ($this->isTableEmpty($dataTable)) {
-            $referrersDataTable = ReferrersAPI::getInstance()->getKeywordsFromCampaignId($idSite, $period, $date, $idSubtable, $segment);
```
Comment (diosmosis) [inline API.php:53]: If this is a proxysite issue, it could (maybe) be fixed by sending a proxy request (by using `Request::processRequest` here, instead of using the API directly. Is there a reason for not doing this?

File: tests/System/expected/test___MarketingCampaignsReporting.getKeywordContentFromNameId_month.xml [hunk 2]
```diff
@@ -0,0 +1,2 @@
+<?xml version="1.0" encoding="utf-8" ?>
+<result />
```
Comment (diosmosis) [inline tests/System/expected/test___MarketingCampaignsReporting.getKeywordContentFromNameId_month.xml:2]: Is there a way to make this test have data in it?

Comment (sgiehl) [reply tests/System/expected/test___MarketingCampaignsReporting.getKeywordContentFromNameId_month.xml:2]: Actually it's on purpose to have no results here, as we send an invalid subtable id. could also add a test that actually has some data

**Comment by sgiehl** [comment]
Thought again about that whole change. Guess we actually need to fix that issue in core. Nevertheless I've changed the PR here again, so the fallback works better.

Note: The tests are now failing. But they should be working again, once https://github.com/matomo-org/matomo/pull/16235 is merged

**Comment by tsteur** [comment]
@sgiehl looks good to merge but there's a merge conflict
